"""add tenant tax invoice fields

Revision ID: 0e1fcf93bb93
Revises: dde9aeb17144
Create Date: 2026-08-13 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1fcf93bb93'
down_revision: Union[str, None] = 'dde9aeb17144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('tax_id', sa.String(length=13), nullable=True))
    op.add_column('tenants', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('branch_code', sa.String(length=10), nullable=True))
    op.add_column('tenants', sa.Column('receipt_footer', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'receipt_footer')
    op.drop_column('tenants', 'branch_code')
    op.drop_column('tenants', 'address')
    op.drop_column('tenants', 'tax_id')
    # ### end Alembic commands ###
