"""add tenant promptpay_id

Revision ID: 0ef3de49acbd
Revises: e50ec06ad8a0
Create Date: 2026-08-01 21:17:13.948394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef3de49acbd'
down_revision: Union[str, None] = 'e50ec06ad8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('promptpay_id', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'promptpay_id')
    # ### end Alembic commands ###
