"""add barcode lookup cache table

Revision ID: 769394cd3910
Revises: 4d885918cc82
Create Date: 2026-08-03 23:07:42.268420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769394cd3910'
down_revision: Union[str, None] = '4d885918cc82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barcode_lookup_cache',
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('found', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('barcode')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barcode_lookup_cache')
    # ### end Alembic commands ###
