"""add sale tax fields and sale_item discount/refunded_qty

Revision ID: a13286ce38ab
Revises: 769394cd3910
Create Date: 2026-08-04 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13286ce38ab'
down_revision: Union[str, None] = '769394cd3910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_items', sa.Column('discount', sa.Numeric(12, 2), nullable=False, server_default='0'))
    op.add_column('sale_items', sa.Column('refunded_qty', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sales', sa.Column('tax', sa.Numeric(12, 2), nullable=False, server_default='0'))
    op.add_column('sales', sa.Column('tax_rate_snapshot', sa.Numeric(5, 2), nullable=False, server_default='0'))
    op.add_column(
        'sales', sa.Column('price_includes_tax_snapshot', sa.Boolean(), nullable=False, server_default='true')
    )
    op.add_column('sales', sa.Column('refunded_total', sa.Numeric(12, 2), nullable=False, server_default='0'))
    # New SaleStatus values. Postgres requires ADD VALUE to run outside any
    # transaction that later uses the new value, so this migration only adds
    # the enum labels — nothing writes them yet.
    op.execute("ALTER TYPE salestatus ADD VALUE IF NOT EXISTS 'partially_refunded'")
    op.execute("ALTER TYPE salestatus ADD VALUE IF NOT EXISTS 'refunded'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'refunded_total')
    op.drop_column('sales', 'price_includes_tax_snapshot')
    op.drop_column('sales', 'tax_rate_snapshot')
    op.drop_column('sales', 'tax')
    op.drop_column('sale_items', 'refunded_qty')
    op.drop_column('sale_items', 'discount')
    # NOTE: Postgres cannot drop individual enum values, so 'partially_refunded'
    # and 'refunded' remain on the salestatus type after downgrade.
    # ### end Alembic commands ###
