"""add refunds and refund_items tables

Revision ID: ab78a4348e2f
Revises: a13286ce38ab
Create Date: 2026-08-04 10:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ab78a4348e2f'
down_revision: Union[str, None] = 'a13286ce38ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'refunds',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('sale_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('client_uuid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('reason', sa.String(length=255), nullable=True),
        sa.Column('refund_amount', sa.Numeric(12, 2), nullable=False),
        sa.Column('refund_tax', sa.Numeric(12, 2), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['sale_id'], ['sales.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_refunds_tenant_id'), 'refunds', ['tenant_id'])
    op.create_index(op.f('ix_refunds_sale_id'), 'refunds', ['sale_id'])
    op.create_index(op.f('ix_refunds_client_uuid'), 'refunds', ['client_uuid'], unique=True)

    op.create_table(
        'refund_items',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('refund_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('sale_item_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('qty', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Numeric(12, 2), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.ForeignKeyConstraint(['refund_id'], ['refunds.id']),
        sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_refund_items_tenant_id'), 'refund_items', ['tenant_id'])
    op.create_index(op.f('ix_refund_items_refund_id'), 'refund_items', ['refund_id'])
    op.create_index(op.f('ix_refund_items_sale_item_id'), 'refund_items', ['sale_item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund_items')
    op.drop_table('refunds')
    # ### end Alembic commands ###
