"""add product expiry_date

Revision ID: dde9aeb17144
Revises: d2e8b4c1f5a7
Create Date: 2026-08-13 14:22:44.700068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde9aeb17144'
down_revision: Union[str, None] = 'd2e8b4c1f5a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('expiry_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'expiry_date')
    # ### end Alembic commands ###
