"""add customers and loyalty points

Revision ID: de6381633f78
Revises: fb41af026646
Create Date: 2026-08-07 14:05:49.898172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de6381633f78'
down_revision: Union[str, None] = 'fb41af026646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('points_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'phone', name='uq_customers_tenant_phone')
    )
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.add_column('sales', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.add_column('sales', sa.Column('points_earned', sa.Integer(), server_default='0', nullable=False))
    op.add_column('sales', sa.Column('points_redeemed', sa.Integer(), server_default='0', nullable=False))
    op.add_column('sales', sa.Column('points_discount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_foreign_key('fk_sales_customer_id_customers', 'sales', 'customers', ['customer_id'], ['id'])
    op.add_column('tenants', sa.Column('loyalty_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tenants', sa.Column('baht_per_point', sa.Numeric(precision=10, scale=2), server_default='25.00', nullable=False))
    op.add_column('tenants', sa.Column('point_value_baht', sa.Numeric(precision=10, scale=2), server_default='1.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'point_value_baht')
    op.drop_column('tenants', 'baht_per_point')
    op.drop_column('tenants', 'loyalty_enabled')
    op.drop_constraint('fk_sales_customer_id_customers', 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_column('sales', 'points_discount')
    op.drop_column('sales', 'points_redeemed')
    op.drop_column('sales', 'points_earned')
    op.drop_column('sales', 'customer_id')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
