"""add tenant vat settings

Revision ID: fb41af026646
Revises: ab78a4348e2f
Create Date: 2026-08-04 10:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb41af026646'
down_revision: Union[str, None] = 'ab78a4348e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('vat_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('tenants', sa.Column('vat_rate', sa.Numeric(5, 2), nullable=False, server_default='7.00'))
    op.add_column('tenants', sa.Column('price_includes_tax', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'price_includes_tax')
    op.drop_column('tenants', 'vat_rate')
    op.drop_column('tenants', 'vat_enabled')
    # ### end Alembic commands ###
